package com.rhys.obd2.data

import android.content.Context
import com.rhys.obd2.obd.Dtc
import com.rhys.obd2.obd.MonitorTest
import com.rhys.obd2.obd.Readiness
import com.rhys.obd2.obd.VehicleInfo
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Builds a plain-text snapshot of everything the app currently knows about the car.
 *
 * This exists because of a genuinely destructive gap in the normal workflow: clearing
 * fault codes erases the codes, the freeze frame and the readiness state, and that is the
 * only record of the fault that exists anywhere. Telling people to "write them down
 * first" is the standard advice and nobody does it. One button that captures the lot is
 * a better answer, and it doubles as something you can send to a garage before paying
 * them to read the same codes again.
 *
 * Deliberately plain text rather than a PDF or a proprietary format: it pastes into an
 * email, a forum post or a WhatsApp message without anyone needing this app to read it.
 */
object DiagnosticReport {

    fun build(
        vehicle: VehicleInfo?,
        dtcs: DtcSnapshot?,
        readiness: Readiness?,
        freezeFrame: FreezeFrame?,
        monitorTests: List<MonitorTest>,
        units: UnitSystem,
    ): String = buildString {
        val stamp = SimpleDateFormat("d MMMM yyyy 'at' HH:mm", Locale.UK).format(Date())

        appendLine("VEHICLE DIAGNOSTIC REPORT")
        appendLine("Generated by OpenOBD on $stamp")
        appendLine("=".repeat(60))
        appendLine()

        vehicleSection(vehicle)
        faultSection(dtcs)
        freezeFrameSection(freezeFrame, units)
        readinessSection(readiness)
        monitorSection(monitorTests)

        appendLine("-".repeat(60))
        appendLine(
            "Read over the standard OBD-II interface. Covers emissions-related systems " +
                "only — it does not include ABS, airbag or other manufacturer-specific " +
                "modules, so an empty report here does not mean the car has no faults at all."
        )
    }

    private fun StringBuilder.vehicleSection(vehicle: VehicleInfo?) {
        appendLine("VEHICLE")
        appendLine("-".repeat(60))
        if (vehicle == null) {
            appendLine("Not read.")
            appendLine()
            return
        }
        line("VIN", vehicle.vin ?: "not reported by this car")
        vehicle.decodedVin?.let { details ->
            details.manufacturer?.let { line("Manufacturer", it) }
            details.modelYear?.let { line("Model year", it) }
            line("Built for", details.region)
        }
        line("Fuel type", vehicle.fuelType ?: "not reported")
        line("OBD standard", vehicle.obdStandard ?: "not reported")
        line("Protocol", vehicle.protocol ?: "unknown")
        line("Adapter", vehicle.adapter ?: "unknown")
        line("Battery voltage", vehicle.batteryVoltage ?: "not read")
        vehicle.ecuName?.let { line("Engine ECU", it) }
        vehicle.calibrationIds.forEachIndexed { i, id ->
            line(if (i == 0) "Calibration ID" else "Calibration ID ${i + 1}", id)
        }
        appendLine()
    }

    private fun StringBuilder.faultSection(dtcs: DtcSnapshot?) {
        appendLine("FAULT CODES")
        appendLine("-".repeat(60))
        if (dtcs == null) {
            appendLine("Not read.")
            appendLine()
            return
        }

        line("Engine management light", if (dtcs.milOn) "ON" else "off")
        appendLine()

        if (dtcs.total == 0) {
            appendLine("No fault codes stored.")
            appendLine()
            return
        }

        codeList("Confirmed faults (turn the light on)", dtcs.stored)
        codeList("Pending faults (seen once, not yet confirmed)", dtcs.pending)
        codeList("Permanent codes (cannot be cleared with a scan tool)", dtcs.permanent)
    }

    private fun StringBuilder.codeList(heading: String, codes: List<Dtc>) {
        if (codes.isEmpty()) return
        appendLine(heading)
        codes.sortedBy { it.severity.ordinal }.forEach { dtc ->
            appendLine("  ${dtc.code}  ${dtc.description}")
            appendLine("      Severity: ${dtc.severity.label}")
            if (dtc.manufacturerSpecific) {
                appendLine("      Manufacturer-specific code — meaning varies by make.")
            }
            dtc.advice?.let { appendLine("      ${wrap(it, 68, "      ")}") }
        }
        appendLine()
    }

    private fun StringBuilder.freezeFrameSection(frame: FreezeFrame?, units: UnitSystem) {
        if (frame == null || frame.values.isEmpty()) return
        appendLine("FREEZE FRAME")
        appendLine("-".repeat(60))
        appendLine(
            frame.triggerCode?.let { "Conditions recorded when $it was stored:" }
                ?: "Conditions recorded when the fault was stored:"
        )
        frame.values.forEach { (pid, readings) ->
            val reading = readings.firstOrNull() ?: return@forEach
            val converted = Units.convert(reading.value, reading.unit, units)
            val value = reading.text
                ?: "${Units.format(converted.value, converted.unit)} ${converted.unit}".trim()
            line("  ${pid.name}", value)
        }
        appendLine()
    }

    private fun StringBuilder.readinessSection(readiness: Readiness?) {
        if (readiness == null) return
        appendLine("EMISSIONS READINESS")
        appendLine("-".repeat(60))
        line("Engine type", if (readiness.compressionIgnition) "Compression ignition (diesel)" else "Spark ignition (petrol)")
        line(
            "Monitors complete",
            "${readiness.supportedMonitors.size - readiness.incompleteCount} of ${readiness.supportedMonitors.size}",
        )
        appendLine()
        readiness.supportedMonitors.forEach { monitor ->
            appendLine("  [${if (monitor.complete) "x" else " "}] ${monitor.name}")
        }
        appendLine()
        if (readiness.incompleteCount > 0) {
            appendLine(
                wrap(
                    "${readiness.incompleteCount} monitor(s) have not finished running. This usually " +
                        "means the codes were cleared or the battery disconnected recently, and it can " +
                        "fail an emissions test on its own.",
                    68,
                    "",
                )
            )
            appendLine()
        }
    }

    private fun StringBuilder.monitorSection(tests: List<MonitorTest>) {
        if (tests.isEmpty()) return
        appendLine("ON-BOARD TEST RESULTS (service 06)")
        appendLine("-".repeat(60))
        appendLine("Measured values against the limits the car judges them by.")
        appendLine()
        tests.groupBy { it.monitorName }.forEach { (monitor, results) ->
            appendLine("  $monitor")
            results.forEach { test ->
                val limits = listOfNotNull(
                    test.min?.let { "min ${format(it)}" },
                    test.max?.let { "max ${format(it)}" },
                ).joinToString(", ").ifEmpty { "no limits reported" }
                val verdict = if (test.passed) "pass" else "FAIL"
                appendLine("      ${test.testName}: ${format(test.value)} ${test.unit} ($limits) — $verdict")
            }
            appendLine()
        }
    }

    private fun StringBuilder.line(label: String, value: String) {
        appendLine(label.padEnd(24) + value)
    }

    private fun format(value: Double): String = when {
        kotlin.math.abs(value) >= 1000 -> "%.0f".format(Locale.UK, value)
        kotlin.math.abs(value) >= 10 -> "%.2f".format(Locale.UK, value)
        else -> "%.4f".format(Locale.UK, value).trimEnd('0').trimEnd('.')
    }

    /** Soft-wraps advice text so the report stays readable in a fixed-width view. */
    private fun wrap(text: String, width: Int, indent: String): String {
        val words = text.split(' ')
        val out = StringBuilder()
        var lineLength = 0
        words.forEach { word ->
            if (lineLength + word.length + 1 > width) {
                out.append("\n").append(indent)
                lineLength = indent.length
            } else if (lineLength > 0) {
                out.append(" ")
                lineLength++
            }
            out.append(word)
            lineLength += word.length
        }
        return out.toString()
    }

    /** Writes the report where the FileProvider can share it from. */
    fun save(context: Context, text: String): File {
        val directory = File(context.filesDir, "reports").apply { mkdirs() }
        val stamp = SimpleDateFormat("yyyy-MM-dd_HHmmss", Locale.UK).format(Date())
        val file = File(directory, "diagnostic_report_$stamp.txt")
        file.writeText(text)
        return file
    }
}
